

server:
  port: 20001
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/education?serverTimezone=GMT&amp;useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456